version: '3.1'
services:
  todobackend:
    image: dieter1199/verteilte-systeme
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=secret
      - DATABASE_NAME=postgres
      - DATABASE_PORT=5432

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: admin
      POSTGRES_DB: postgres

  frontend:
    image: dieter1199/verteilte-systeme-nginx
    ports:
      - 80:80
    environment:
      - API_URL=https://todobackend:8080/api/todos
